/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Professor
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCadastroC = new javax.swing.JMenuItem();
        MenuCadastroF = new javax.swing.JMenuItem();
        MenuCadastroP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCalculadora = new javax.swing.JMenu();
        menucalculadora1 = new javax.swing.JMenuItem();
        jmenudesenv = new javax.swing.JMenu();
        MenuDesenvolvedor = new javax.swing.JMenuItem();
        jmenuajuda = new javax.swing.JMenu();
        MenuAjuda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        MenuCadastroC.setText("Cadastrar Cliente");
        MenuCadastroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroCActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastroC);

        MenuCadastroF.setText("Cadastrar Fornecedor");
        MenuCadastroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroFActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastroF);

        MenuCadastroP.setText("Cadastrar Produto");
        MenuCadastroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastroP);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        MenuCalculadora.setText("Calculadora");
        MenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculadoraActionPerformed(evt);
            }
        });

        menucalculadora1.setText("Calculadora");
        menucalculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucalculadora1ActionPerformed(evt);
            }
        });
        MenuCalculadora.add(menucalculadora1);

        jMenuBar1.add(MenuCalculadora);

        jmenudesenv.setText("Desenvolvedor");
        jmenudesenv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenudesenvActionPerformed(evt);
            }
        });

        MenuDesenvolvedor.setText("Desenvolvedor");
        MenuDesenvolvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDesenvolvedorActionPerformed(evt);
            }
        });
        jmenudesenv.add(MenuDesenvolvedor);

        jMenuBar1.add(jmenudesenv);

        jmenuajuda.setText("Ajuda");
        jmenuajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuajudaActionPerformed(evt);
            }
        });

        MenuAjuda.setText("Ajuda");
        MenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaActionPerformed(evt);
            }
        });
        jmenuajuda.add(MenuAjuda);

        jMenuBar1.add(jmenuajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroCActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_MenuCadastroCActionPerformed

    private void MenuCadastroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroFActionPerformed
        CadastroFornecedor cadastroFornecedor = new CadastroFornecedor();
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_MenuCadastroFActionPerformed

    private void MenuCadastroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroPActionPerformed
        
    }//GEN-LAST:event_MenuCadastroPActionPerformed

    private void jmenuajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuajudaActionPerformed
        
    }//GEN-LAST:event_jmenuajudaActionPerformed

    private void jmenudesenvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenudesenvActionPerformed
        
    }//GEN-LAST:event_jmenudesenvActionPerformed

    private void MenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculadoraActionPerformed
        
    }//GEN-LAST:event_MenuCalculadoraActionPerformed

    private void MenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaActionPerformed
        Ajuda ajuda = new Ajuda();
        ajuda.setVisible(true);
    }//GEN-LAST:event_MenuAjudaActionPerformed

    private void menucalculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucalculadora1ActionPerformed
       Calculadora calculadora = new Calculadora();
       calculadora.setVisible(true);
    }//GEN-LAST:event_menucalculadora1ActionPerformed

    private void MenuDesenvolvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDesenvolvedorActionPerformed
        Desenvolvedor desenvolvedor = new Desenvolvedor();
        desenvolvedor.setVisible(true);
    }//GEN-LAST:event_MenuDesenvolvedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAjuda;
    private javax.swing.JMenuItem MenuCadastroC;
    private javax.swing.JMenuItem MenuCadastroF;
    private javax.swing.JMenuItem MenuCadastroP;
    private javax.swing.JMenu MenuCalculadora;
    private javax.swing.JMenuItem MenuDesenvolvedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmenuajuda;
    private javax.swing.JMenu jmenudesenv;
    private javax.swing.JMenuItem menucalculadora1;
    // End of variables declaration//GEN-END:variables
}
